изменил модели получения данных,
ernest1818/VK_Application pull request #6
Opened 2022-11-25 13:27 UTC by ernest1818

раскидал данные по приложению,
загрузил фото,
установил Realm

https://user-images.githubusercontent.com/109942907/203995416-cb8e2f58-6e39-4cc5-a041-b0001c78ba4e.mp4

2022-11-25 13:57 UTC, valadzko requested changes
очень мало файлов, ты очевидно не закоммитил большую часть проекта - нет контроллеров

2022-11-25 13:57 UTC, valadzko commented on VK_App/VK_App/Information/Friends.swift
> +import Foundation
похоже что ты забыл сюда перенести структуру

2022-11-25 13:57 UTC, valadzko commented on VK_App/VK_App/Information/Friend.swift
> +//  Friend.swift
должен линтер тут отработать, в других местах тоже

2022-11-25 13:57 UTC, valadzko commented on VK_App/VK_App/Information/Friend.swift
> +import Foundation
тут тоже нет класса или структуры, а еще если больше не будет ничего - то попробуй удалить импорт Foundation он нужен не всегда, и ненужные импорты нам точно не нужны

2022-11-25 13:57 UTC, valadzko commented on VK_App/VK_App/Information/FriendsInformation.swift
> +///
тут описания забыл допричесывать, посмотри весь проект на комментарии, если что пропустишь я напишу в каждом месте во время проверки после твоих фиксов.

2022-11-25 13:57 UTC, valadzko commented on VK_App/VK_App/Information/FriendsInformation.swift
> +///
тут описания забыл допричесывать, посмотри весь проект на комментарии, если что пропустишь я напишу в каждом месте во время проверки после твоих фиксов.

2022-11-25 13:57 UTC, valadzko commented on VK_App/VK_App/Information/FriendsInformation.swift
> +class FriendResponse: Decodable {
классы мы все делаем final, тоже проверь весь проект

2022-11-25 13:57 UTC, valadzko commented on VK_App/VK_App/Information/FriendsInformation.swift
> +        case firstName = "first_name"
по идее для firstName, lastName должно работать и без ключей, то есть он должен сам преобразовывать firstName в first_name и наоборот

2022-11-25 13:57 UTC, valadzko commented on VK_App/VK_App/Information/FriendsInformation.swift
> +    var count: Int
еще возможно где-то можно поменять var на let, не уверен что это тут, но скорее всего в классах наших моделей это можно где-то сделать. и если найдёшь такие моменты - let переменные должны будут идти выше var

2022-11-25 13:57 UTC, valadzko commented on VK_App/VK_App/Information/GroupsInformation/GroupInformation.swift
> +
файл лучше заканчивать 1 пустой строкой, 2 - слишком много, 0 тоже не очень (могу обьяснить если будет желание, но там супер редкие случаи)

2022-11-25 14:53 UTC, valadzko commented
начальный экран стоит уже переключить на дефолтный логин вк - а этот наш самописный стоит убрать, можно даже из проекта вообще

2022-11-25 18:44 UTC, valadzko requested changes

2022-11-25 18:44 UTC, valadzko commented on VK_App/VK_App/Controller/UserGroupTableViewController.swift
> +        fetchResponse()
лучше указать чего именно фетч fetchGroups или fetchPublicGroups, fetchGlobalGroups

2022-11-25 18:44 UTC, valadzko commented on VK_App/VK_App/Controller/UserImageCollectionViewController.swift
> +            let imageUrl = photoUserUrl[indexPath.row].sizes.last
я бы еще добавлял проверку что photoUserUrl.indices.contains(indexPath.row) в guard

2022-11-25 18:44 UTC, valadzko commented on VK_App/VK_App/Controller/UserImageCollectionViewController.swift
> +        userImageVC.configure(indexPath: indexPath, content: photoUserUrl)
лучше назвать userPhotoURL или userPhotoURLName если это не URL объект а стринг

2022-11-25 18:44 UTC, valadzko commented on VK_App/VK_App/Controller/UserImageViewController.swift
> +    private var contentImageNames: [Photo]?
можно просто imageNames, и вообще тут написано imageNames а справа [Photo] может и тут лучше photos или photoNames, вообще если объект а не строка - то пишем по названию обьекта

2022-11-25 18:44 UTC, valadzko commented on VK_App/VK_App/Controller/UserImageViewController.swift
> +        NetworkService.instance.downLoadImage(url: contentImageNames?[rowIndex].sizes.last?.url ?? "") { image in
тут лучше guard на проверку url и выход, чем передавать пустую строку и грузить по этой пустой строке что-то

2022-11-25 18:44 UTC, valadzko commented on VK_App/VK_App/Controller/UserImageViewController.swift
> +//            self.imageView.image = UIImage(named: self.contentImageNames?[self.rowIndex] ?? "")
коменты удаляем

2022-11-25 18:44 UTC, valadzko commented on VK_App/VK_App/Controller/UserImageViewController.swift
> +                .downLoadImage(url: self?.contentImageNames?[self?.rowIndex ?? 0].sizes.last?.url ?? "") { image in
очень много ? ??, лучше пользуйся гуардом где можно, если данные вообще не валидны - лучше выходить из функции чем подставлять 0 или ""

2022-11-25 18:44 UTC, valadzko commented on VK_App/VK_App/Controller/UserImageViewController.swift
> +                .downLoadImage(url: self?.contentImageNames?[self?.rowIndex ?? 0].sizes.last?.url ?? "") { image in
правильно download, а не downLoad

2022-11-25 18:44 UTC, valadzko commented on VK_App/VK_App/Information/GroupsInformation/Group.swift
> +    @objc dynamic var groupName: String
я считаю что можно просто назвать name, и imageName,
тк дублирование названия класса в его полях плохая практика, тогда кстати и ключ можно удалить тк будут совпадать названия

2022-11-25 18:44 UTC, valadzko commented on VK_App/VK_App/Information/GroupsInformation/Groups.swift
> +    var count: Int
непонятно зачем count, если есть items.count

2022-11-25 18:44 UTC, valadzko commented on VK_App/VK_App/Information/PhotoInformation/PhotoInformation.swift
> +/// Ответ  серера о фотографиях пользователя
опечатка, другие респонзы (где в названии response) тоже лучше так описать - что это ответ сервера 
```suggestion
/// Ответ сервера о фотографиях пользователя
```

2022-11-25 18:44 UTC, valadzko commented on VK_App/VK_App/Information/PhotoInformation/PhotoURL.swift
> +class PhotoUrl: Object, Decodable {
классы все final где это можно

2022-11-25 18:44 UTC, valadzko commented on VK_App/VK_App/NetworkService/NetworkService.swift
> +                print("error datatatatta", error)
```suggestion
                print("error - (error.localizedDescription)")
```
или как-то так

2022-11-25 18:44 UTC, valadzko commented on VK_App/VK_App/NetworkService/NetworkService.swift
> +        print(token)
ууу, это залет по секьюрити)))

2022-11-25 18:44 UTC, valadzko commented on VK_App/VK_App/NetworkService/NetworkService.swift
> +        let session = URLSession.shared
непонятно зачем эта строка, просто пиши на следующей стразу URLSession.shared.dataTask
читаемость не ухудшится а будет -1 ненужная строка

2022-11-25 18:44 UTC, valadzko commented on VK_App/VK_App/View/FriendsListViewCell.swift
> +    @IBOutlet var firstName: UILabel!
```suggestion
    @IBOutlet var firstNameLabel: UILabel!
```

2022-11-25 18:44 UTC, valadzko commented on VK_App/VK_App/View/OtherGroupsViewCell.swift
> +            self?.otherGroupImageView.image = image
otherGroupImageView лучше как я писал глобалгрупс 
"другие" немного непонятно какие другие

2022-11-25 18:44 UTC, valadzko commented on VK_App/VK_App/Controller/UserImageCollectionViewController.swift
> +            self?.photoUserUrl = photoUrl.response.items
userPhotoURL

2022-11-25 18:44 UTC, valadzko commented on VK_App/VK_App/Controller/UserImageCollectionViewController.swift
> +            ownerIdValue: user?.id ?? 0
надо guard и выход если найди нету, а не запрос с 0 айди

2022-11-25 18:44 UTC, valadzko commented on VK_App/VK_App/Information/Friend.swift
> +        case firstName = "first_name"
как уже писал кажется такому ключу можно не указывать "first_name"

2022-11-25 19:17 UTC, ernest1818 commented on VK_App/VK_App/Controller/FriendsListTableViewController.swift
> +    private func fetchResponse() {
да, перед коммитом тоже так подумал

2022-11-25 19:59 UTC, ernest1818 commented on VK_App/VK_App/Controller/OtherGroupsTableViewController.swift
> +                self?.tableView.reloadData()
мне с дидсетом разобраться еще надо

2022-11-25 20:20 UTC, ernest1818 commented on VK_App/VK_App/Controller/UserImageCollectionViewController.swift
> +            let imageUrl = photoUserUrl[indexPath.row].sizes.last
надо пояснительную бригаду

2022-11-25 20:37 UTC, ernest1818 commented on VK_App/VK_App/NetworkService/NetworkService.swift
> +        print(token)
)))

2022-11-25 20:51 UTC, ernest1818 commented on VK_App/VK_App/Information/Friend.swift
> +        case firstName = "first_name"
можно если декодить в методе, но я этого не делаю

2022-11-26 05:20 UTC, valadzko commented on VK_App/VK_App/View/FriendsListViewCell.swift
> +        NetworkService.instance.downloadImage(url: user.userPhoto ?? "") { image in
загрузка по пустой строке не нужна, нужно как можно раньше фейлить если есть ошибка чтобы ее можно было легче найти - тут нужен guard

2022-11-26 05:20 UTC, valadzko commented on VK_App/VK_App/Information/Friend.swift
> +        case firstName = "first_name"
нашел что тогда нужно декодер настраивать вот так
https://www.hackingwithswift.com/articles/119/codable-cheat-sheet

2022-11-26 05:20 UTC, valadzko commented on VK_App/VK_App/Information/Friend.swift
> +        case firstName = "first_name"
так что лучше тут оставлять все как есть

2022-11-26 05:20 UTC, valadzko commented on VK_App/VK_App/View/OtherGroupsViewCell.swift
>  final class OtherGroupsViewCell: UITableViewCell {
```suggestion
final class GlobalGroupsViewCell: UITableViewCell {
```
и название файла тоже, лучше чтобы все однинаковыми словами называлось, иначе кажется что разные сущности

2022-11-26 05:20 UTC, valadzko commented on VK_App/VK_App/NetworkService/NetworkService.swift
> +    func downloadImage(url: String, completion: @escaping (_ image: UIImage) -> ()) {
а как это он не импортирует UIKit но использует UIImage. 
Вобщем лучше конечно не возвращать UI элементы из слоя модели, тут только данные, юай создаем в юае.

2022-11-26 05:20 UTC, valadzko commented on VK_App/VK_App/Controller/UserImageCollectionViewController.swift
> +    override func viewDidLoad() {
потерялась марка Lifecycle

2022-11-26 07:39 UTC, valadzko approved these changes
эти коменты уже опциональные

2022-11-26 07:39 UTC, valadzko commented on VK_App/VK_App/Controller/FriendsListTableViewController.swift
> +            DispatchQueue.main.async {
**View controller functions, button actions, etc are always called on the main thread.**
не нужно оборачивать ` tableView.reloadData()` в .main.async

просто вот так:
```
didSet {
    tableView.reloadData()
}
```

2022-11-26 07:39 UTC, valadzko commented on VK_App/VK_App/Controller/FriendsListTableViewController.swift
> +        NetworkService.instance.fetchRequest(request: .friendsList) { [weak self] (users: FriendsResponse) in
```suggestion
        NetworkService.instance.fetch(request: .friendsList) { [weak self] (users: FriendsResponse) in
```

2022-11-26 07:39 UTC, valadzko commented on VK_App/VK_App/Controller/GlobalGroupsTableViewController.swift
> +    var globalGroups: [Group] = .init()
```suggestion
    var globalGroups: [Group] = []
```

2022-11-26 07:39 UTC, valadzko commented on VK_App/VK_App/Controller/UserGroupTableViewController.swift
>                  tableView.reloadData()
тоже лучше просто добавь didSet в  filterGroups и в userGroups и удали в других местах

2022-11-26 07:48 UTC, ernest1818 commented on VK_App/VK_App/Controller/FriendsListTableViewController.swift
> +            DispatchQueue.main.async {
@valadzko если без то таблица откроется пустой, и после загрузки ничего не поменяется

2022-11-26 07:51 UTC, ernest1818 commented on VK_App/VK_App/Controller/UserGroupTableViewController.swift
>                  tableView.reloadData()
я пока так оставлю, что бы не путаться

2022-11-28 08:36 UTC, AlexanderKokh commented on VK_App/VK_App/Controller/FriendsListTableViewController.swift
> +        NetworkService.instance.fetchRequest(request: .friendsList) { [weak self] (users: FriendsResponse) in
```suggestion
        NetworkService.instance.fetchRequest(request: .friendsList) { [weak self] (users: FriendsResponse) in
        guard let self = self else { return }
```

2022-11-28 08:36 UTC, AlexanderKokh commented on VK_App/VK_App/Controller/GlobalGroupsTableViewController.swift
> +extension GlobalGroupsTableViewController: UISearchBarDelegate {
Описание

2022-11-28 08:36 UTC, AlexanderKokh commented on VK_App/VK_App/Controller/GlobalGroupsTableViewController.swift
> +                self?.filterGroups = searchGroups.response.items
```suggestion
                guard let self = self else { return }
                self?.filterGroups = searchGroups.response.items
```

2022-11-28 08:36 UTC, AlexanderKokh commented on VK_App/VK_App/Controller/UserGroupTableViewController.swift
> +            self?.userGroups = groups.response.items
```suggestion
           guard let self = self else { return }
            self?.userGroups = groups.response.items
```

2022-11-28 08:36 UTC, AlexanderKokh commented on VK_App/VK_App/Controller/UserImageCollectionViewController.swift
> +    private var photoUserUrlNames: [Photo] = []
```suggestion
    private var photos: [Photo] = []
```

2022-11-28 08:36 UTC, AlexanderKokh commented on VK_App/VK_App/Controller/UserImageCollectionViewController.swift
> +            self?.photoUserUrlNames = userPhotoUrl.response.items
```suggestion
          guard let self = self else { return }
            self?.photoUserUrlNames = userPhotoUrl.response.items
```

2022-11-28 08:36 UTC, AlexanderKokh commented on VK_App/VK_App/Controller/UserImageViewController.swift
> +        UIView.animate(withDuration: 0.5) { [weak self] in
```suggestion
        UIView.animate(withDuration: 0.5) { _ in
```

2022-11-28 08:36 UTC, AlexanderKokh commented on VK_App/VK_App/Controller/UserImageViewController.swift
> +                .downloadImage(url: url) { imageData in
```suggestion
                .downloadImage(url: url) { [weak self] imageData in
```

2022-11-28 08:36 UTC, AlexanderKokh commented on VK_App/VK_App/NetworkService/NetworkService.swift
> +        AF.request(url, parameters: parameters).responseData { [weak self] response in
```suggestion
        AF.request(url, parameters: parameters).responseData {  response in
```

2022-11-28 08:36 UTC, AlexanderKokh commented on VK_App/VK_App/NetworkService/NetworkService.swift
> +                print("error - \(error.localizedDescription)")
```suggestion
                print("\(error.localizedDescription)")
```
либо убирай, либо в константы

2022-11-28 09:37 UTC, AlexanderKokh approved these changes

2022-11-28 10:08 UTC, merged